### ISSUE TITLE
Is this module supposed to alert users to firmware upgrades that are not "critical"?

### ISSUE THREAD

**Issue by puterboy** [OctoPrint/OctoPrint-FirmwareCheck#3]
Just asking because  I didn't get any alert of the new Prusa firmware upgrades even though they incorporate some important safety considerations improving detection of thermal runaway.

More generally, it would be great if this plugin could alert for any (relevant) firmware upgrades.

Am I doing something wrong or missing the point of this module?

**Comment by jneilliii** [comment]
It does not. The Firmware Check plugin is to be able to warn of mis-behaving firmware and provide links to plugins for potential fixes (ie Creality and the 2x temp fix plugin). It's outline pretty well what the intent of this plugin is [here](https://github.com/OctoPrint/OctoPrint-FirmwareCheck#firmware-check).

**Comment by cp2004** [comment]
Checking for updates for printer firmware would not be something this plugin could do - there are infinitely many sources of firmware for different printers that it would be nearly impossible to provide something that actually worked accurately here.

I wouldn't consider previous Prusa firmware 'unsafe' because it doesn't have the improvements, so the plugin doesn't need to warn about this. They are extra nice to have things - otherwise I would think Prusa would have strongly advised upgrading.
